// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/ai_model_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mensagem para CreateAIModel
type CreateAIModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PerfilName    string                 `protobuf:"bytes,1,opt,name=perfilName,proto3" json:"perfilName,omitempty"`
	Instructions  string                 `protobuf:"bytes,2,opt,name=instructions,proto3" json:"instructions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAIModelRequest) Reset() {
	*x = CreateAIModelRequest{}
	mi := &file_proto_ai_model_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAIModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAIModelRequest) ProtoMessage() {}

func (x *CreateAIModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_model_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAIModelRequest.ProtoReflect.Descriptor instead.
func (*CreateAIModelRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_model_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAIModelRequest) GetPerfilName() string {
	if x != nil {
		return x.PerfilName
	}
	return ""
}

func (x *CreateAIModelRequest) GetInstructions() string {
	if x != nil {
		return x.Instructions
	}
	return ""
}

type GetPerfilModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPerfilModelsRequest) Reset() {
	*x = GetPerfilModelsRequest{}
	mi := &file_proto_ai_model_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPerfilModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPerfilModelsRequest) ProtoMessage() {}

func (x *GetPerfilModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_model_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPerfilModelsRequest.ProtoReflect.Descriptor instead.
func (*GetPerfilModelsRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_model_service_proto_rawDescGZIP(), []int{1}
}

type AIModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PerfilName    string                 `protobuf:"bytes,2,opt,name=perfilName,proto3" json:"perfilName,omitempty"`
	Instructions  string                 `protobuf:"bytes,3,opt,name=instructions,proto3" json:"instructions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIModel) Reset() {
	*x = AIModel{}
	mi := &file_proto_ai_model_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIModel) ProtoMessage() {}

func (x *AIModel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_model_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIModel.ProtoReflect.Descriptor instead.
func (*AIModel) Descriptor() ([]byte, []int) {
	return file_proto_ai_model_service_proto_rawDescGZIP(), []int{2}
}

func (x *AIModel) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AIModel) GetPerfilName() string {
	if x != nil {
		return x.PerfilName
	}
	return ""
}

func (x *AIModel) GetInstructions() string {
	if x != nil {
		return x.Instructions
	}
	return ""
}

type GetPerfilModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*AIModel             `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPerfilModelsResponse) Reset() {
	*x = GetPerfilModelsResponse{}
	mi := &file_proto_ai_model_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPerfilModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPerfilModelsResponse) ProtoMessage() {}

func (x *GetPerfilModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_model_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPerfilModelsResponse.ProtoReflect.Descriptor instead.
func (*GetPerfilModelsResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_model_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetPerfilModelsResponse) GetModels() []*AIModel {
	if x != nil {
		return x.Models
	}
	return nil
}

type GetAIModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAIModelsResponse) Reset() {
	*x = GetAIModelsResponse{}
	mi := &file_proto_ai_model_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAIModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAIModelsResponse) ProtoMessage() {}

func (x *GetAIModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_model_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAIModelsResponse.ProtoReflect.Descriptor instead.
func (*GetAIModelsResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_model_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetAIModelsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_ai_model_service_proto protoreflect.FileDescriptor

const file_proto_ai_model_service_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/ai_model_service.proto\x12\x05model\"Z\n" +
	"\x14CreateAIModelRequest\x12\x1e\n" +
	"\n" +
	"perfilName\x18\x01 \x01(\tR\n" +
	"perfilName\x12\"\n" +
	"\finstructions\x18\x02 \x01(\tR\finstructions\"\x18\n" +
	"\x16GetPerfilModelsRequest\"]\n" +
	"\aAIModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1e\n" +
	"\n" +
	"perfilName\x18\x02 \x01(\tR\n" +
	"perfilName\x12\"\n" +
	"\finstructions\x18\x03 \x01(\tR\finstructions\"A\n" +
	"\x17GetPerfilModelsResponse\x12&\n" +
	"\x06models\x18\x01 \x03(\v2\x0e.model.AIModelR\x06models\"-\n" +
	"\x13GetAIModelsResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xb0\x01\n" +
	"\x0eAIModelService\x12P\n" +
	"\x0fGetPerfilModels\x12\x1d.model.GetPerfilModelsRequest\x1a\x1e.model.GetPerfilModelsResponse\x12L\n" +
	"\x11CreatePerfilModel\x12\x1b.model.CreateAIModelRequest\x1a\x1a.model.GetAIModelsResponseB\x12Z\x10gateway-ms/protob\x06proto3"

var (
	file_proto_ai_model_service_proto_rawDescOnce sync.Once
	file_proto_ai_model_service_proto_rawDescData []byte
)

func file_proto_ai_model_service_proto_rawDescGZIP() []byte {
	file_proto_ai_model_service_proto_rawDescOnce.Do(func() {
		file_proto_ai_model_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ai_model_service_proto_rawDesc), len(file_proto_ai_model_service_proto_rawDesc)))
	})
	return file_proto_ai_model_service_proto_rawDescData
}

var file_proto_ai_model_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_ai_model_service_proto_goTypes = []any{
	(*CreateAIModelRequest)(nil),    // 0: model.CreateAIModelRequest
	(*GetPerfilModelsRequest)(nil),  // 1: model.GetPerfilModelsRequest
	(*AIModel)(nil),                 // 2: model.AIModel
	(*GetPerfilModelsResponse)(nil), // 3: model.GetPerfilModelsResponse
	(*GetAIModelsResponse)(nil),     // 4: model.GetAIModelsResponse
}
var file_proto_ai_model_service_proto_depIdxs = []int32{
	2, // 0: model.GetPerfilModelsResponse.models:type_name -> model.AIModel
	1, // 1: model.AIModelService.GetPerfilModels:input_type -> model.GetPerfilModelsRequest
	0, // 2: model.AIModelService.CreatePerfilModel:input_type -> model.CreateAIModelRequest
	3, // 3: model.AIModelService.GetPerfilModels:output_type -> model.GetPerfilModelsResponse
	4, // 4: model.AIModelService.CreatePerfilModel:output_type -> model.GetAIModelsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_ai_model_service_proto_init() }
func file_proto_ai_model_service_proto_init() {
	if File_proto_ai_model_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ai_model_service_proto_rawDesc), len(file_proto_ai_model_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ai_model_service_proto_goTypes,
		DependencyIndexes: file_proto_ai_model_service_proto_depIdxs,
		MessageInfos:      file_proto_ai_model_service_proto_msgTypes,
	}.Build()
	File_proto_ai_model_service_proto = out.File
	file_proto_ai_model_service_proto_goTypes = nil
	file_proto_ai_model_service_proto_depIdxs = nil
}
