// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/whatsapp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateQRCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateQRCodeRequest) Reset() {
	*x = GenerateQRCodeRequest{}
	mi := &file_proto_whatsapp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateQRCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateQRCodeRequest) ProtoMessage() {}

func (x *GenerateQRCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateQRCodeRequest.ProtoReflect.Descriptor instead.
func (*GenerateQRCodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateQRCodeRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type GenerateQRCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QrCode        string                 `protobuf:"bytes,1,opt,name=qr_code,json=qrCode,proto3" json:"qr_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateQRCodeResponse) Reset() {
	*x = GenerateQRCodeResponse{}
	mi := &file_proto_whatsapp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateQRCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateQRCodeResponse) ProtoMessage() {}

func (x *GenerateQRCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whatsapp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateQRCodeResponse.ProtoReflect.Descriptor instead.
func (*GenerateQRCodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_whatsapp_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateQRCodeResponse) GetQrCode() string {
	if x != nil {
		return x.QrCode
	}
	return ""
}

var File_proto_whatsapp_proto protoreflect.FileDescriptor

const file_proto_whatsapp_proto_rawDesc = "" +
	"\n" +
	"\x14proto/whatsapp.proto\x12\bwhatsapp\"9\n" +
	"\x15GenerateQRCodeRequest\x12 \n" +
	"\vphoneNumber\x18\x01 \x01(\tR\vphoneNumber\"1\n" +
	"\x16GenerateQRCodeResponse\x12\x17\n" +
	"\aqr_code\x18\x01 \x01(\tR\x06qrCode2h\n" +
	"\x0fWhatsappService\x12U\n" +
	"\x0eGenerateQRCode\x12\x1f.whatsapp.GenerateQRCodeRequest\x1a .whatsapp.GenerateQRCodeResponse\"\x00B\x1aZ\x18whatsapp-client-ms/protob\x06proto3"

var (
	file_proto_whatsapp_proto_rawDescOnce sync.Once
	file_proto_whatsapp_proto_rawDescData []byte
)

func file_proto_whatsapp_proto_rawDescGZIP() []byte {
	file_proto_whatsapp_proto_rawDescOnce.Do(func() {
		file_proto_whatsapp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_whatsapp_proto_rawDesc), len(file_proto_whatsapp_proto_rawDesc)))
	})
	return file_proto_whatsapp_proto_rawDescData
}

var file_proto_whatsapp_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_whatsapp_proto_goTypes = []any{
	(*GenerateQRCodeRequest)(nil),  // 0: whatsapp.GenerateQRCodeRequest
	(*GenerateQRCodeResponse)(nil), // 1: whatsapp.GenerateQRCodeResponse
}
var file_proto_whatsapp_proto_depIdxs = []int32{
	0, // 0: whatsapp.WhatsappService.GenerateQRCode:input_type -> whatsapp.GenerateQRCodeRequest
	1, // 1: whatsapp.WhatsappService.GenerateQRCode:output_type -> whatsapp.GenerateQRCodeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_whatsapp_proto_init() }
func file_proto_whatsapp_proto_init() {
	if File_proto_whatsapp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_whatsapp_proto_rawDesc), len(file_proto_whatsapp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_whatsapp_proto_goTypes,
		DependencyIndexes: file_proto_whatsapp_proto_depIdxs,
		MessageInfos:      file_proto_whatsapp_proto_msgTypes,
	}.Build()
	File_proto_whatsapp_proto = out.File
	file_proto_whatsapp_proto_goTypes = nil
	file_proto_whatsapp_proto_depIdxs = nil
}
